### ISSUE TITLE
o--if-nojs or o--if-no-js for no script version? 

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-tracking#61]
The example givin under Polyfills & Doesn't cut the mustard has a class of:  `o--if-nojs`. This looks like a typo but just wanted to raise just in case it's not.

**Comment by markstephens** [comment]
Hi Thurston

`o--if-nojs` is the correct class.

The CTM check specifies this in your CSS:
```css
.core .o--if-js,
.enhanced .o--if-no-js { display: none !important; }
```

That means if the CTM check passes and an enhanced class is added to the html tag - the o-tracking html snippet will be hidden which is the correct functionality.

Mark
